# Autogenerated wrapper script for ReadabilityCore_jll for x86_64-w64-mingw32
export libcore_lib

JLLWrappers.@generate_wrapper_header("ReadabilityCore")
JLLWrappers.@declare_file_product(libcore_lib)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        libcore_lib,
        "lib\\libcore_lib.rlib",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
